name: Run react application

on:
  push:
    branches:
      - main

jobs:
  run-application-on-container:
    name: Deploy 
    runs-on: ubuntu-latest

    steps:
      - name: SSH to instance
        env:
           PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           HOSTNAME: ${{secrets.SSH_HOST}}
           USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              cd /home/ubuntu/ &&
              git clone git@github.com:johnsjotm/rsvc_fe.git &&
              cd /home/ubuntu/rsvc_fe &&
              git checkout main && docker compose up -d --no-deps --force-recreate --build react-app
              '
